def test_exception_run():
    pass


def test_exception_capture():
    pass
