
--
DEBUG     2024-07-03 09:05:08  Logging level set to DEBUG
DEBUG     2024-07-03 09:05:08  Created DB link: 'sqlite:///:memory:'
DEBUG     2024-07-03 09:05:08  Using backend: loky
DEBUG     2024-07-03 09:05:08  Executing 10 tasks on 2 workers (backend:loky)
DEBUG     2024-07-03 09:05:09  Encountered exception in task, propagating to main process
DEBUG     2024-07-03 09:05:09  Executed 4 of 10 tasks (40%) with return_as=generator_unordered
TestException at failfast.py:20::faulty_step "<unkown>": test error
--


